export default {
	main: [{
		id: 'userBillCode',
		label: '手工单号',
		type: 'basic'
	}, {
		id: 'businessDate',
		label: '业务时间',
		type: 'basic'
	}, {
		id: 'organ.name',
		label: '收款机构',
		type: 'basic'
	}, {
		id: 'otherOrgan.name',
		label: '付款机构',
		type: 'basic'
	}, {
		id: 'department.name',
		label: '核算部门',
		type: 'basic'
	}, {
		id: 'operateMan.name',
		label: '经办人',
		type: 'basic'
	}, {
		id: 'sourceType',
		label: '业务来源',
		type: 'basic'
	}, {
		id: 'payWay',
		label: '客户支付方式',
		type: 'basic'
	}, {
		id: 'memo',
		label: '备注',
		type: 'basic'
	}],
	details: [{
		id: 'salesPrice',
		label: '非税销售单价'
	}, {
		id: 'taxSalesPrice',
		label: '含税销售单价'
	}, {
		id: 'taxRate',
		label: '税率'
	}, {
		id: 'discountRate',
		label: '折扣率%'
	}, {
		id: 'discountMoney',
		label: '折扣额'
	}, {
		id: 'salesMoney',
		label: '非税销售金额'
	}, {
		id: 'taxRateMoney',
		label: '税额'
	}, {
		id: 'totalMoney',
		label: '价税合计'
	}]
}
