export default {
	OutStore: [{
		step: 1,
		title: '出库数量为0',
		mistakeType: 'remind'
	}, {
		step: 2,
		title: '重复品项',
		mistakeType: 'warn'
	}, {
		step: 3,
		title: '仓库与品项关联关系',
		mistakeType: 'warn'
	}, {
		step: 4,
		title: '出库品项未配货',
		mistakeType: 'remind'
	}, {
		step: 5,
		title: '单价为0',
		mistakeType: 'warn'
	}, {
		step: 6,
		title: '价格差异',
		mistakeType: 'warn'
	}],
	OutStore_Checked: [{
		step: 1,
		title: '出库数量为0',
		mistakeType: 'remind'
	}, {
		step: 2,
		title: '重复品项',
		mistakeType: 'warn'
	}, {
		step: 3,
		title: '仓库与品项关联关系',
		mistakeType: 'warn'
	}, {
		step: 4,
		title: '出库品项未配货',
		mistakeType: 'remind'
	}, {
		step: 5,
		title: '单价为0',
		mistakeType: 'warn'
	}, {
		step: 6,
		title: '价格差异',
		mistakeType: 'warn'
	}, {
		step: 7,
		title: '销售价格小于成本价格',
		mistakeType: 'warn'
	}],
	OutStore_AmountNegative: [{
		step: 1,
		title: '出库数量为0',
		mistakeType: 'remind'
	}, {
		step: 2,
		title: '重复品项',
		mistakeType: 'warn'
	}, {
		step: 3,
		title: '仓库与品项关联关系',
		mistakeType: 'warn'
	}, {
		step: 4,
		title: '出库数量为负库存',
		mistakeType: 'remind'
	}, {
		step: 5,
		title: '出库品项未配货',
		mistakeType: 'remind'
	}, {
		step: 6,
		title: '单价为0',
		mistakeType: 'warn'
	}, {
		step: 7,
		title: '价格差异',
		mistakeType: 'warn'
	}],
	OutStore_Checked_AmountNegative: [{
		step: 1,
		title: '出库数量为0',
		mistakeType: 'remind'
	}, {
		step: 2,
		title: '重复品项',
		mistakeType: 'warn'
	}, {
		step: 3,
		title: '仓库与品项关联关系',
		mistakeType: 'warn'
	}, {
		step: 4,
		title: '出库数量为负库存',
		mistakeType: 'remind'
	}, {
		step: 5,
		title: '出库品项未配货',
		mistakeType: 'remind'
	}, {
		step: 6,
		title: '单价为0',
		mistakeType: 'warn'
	}, {
		step: 7,
		title: '价格差异',
		mistakeType: 'warn'
	}, {
		step: 8,
		title: '销售价格小于成本价格',
		mistakeType: 'warn'
	}]
}
