export default {
	main: [{
		id: 'userBillCode',
		label: '手工单号',
		type: 'basic'
	}, {
		id: 'billTypeName',
		label: '单据类型：',
		type: 'basic'
	}, {
		id: 'billBizTypeName',
		label: '业务类型',
		type: 'basic'
	}, {
		id: 'businessDate',
		label: '业务时间',
		type: 'basic'
	}, {
		id: 'organDetails.organ.name',
		label: '生产机构',
		type: 'basic'
	}, {
		id: 'operateMan.name',
		label: '经办人',
		type: 'basic'
	}, {
		id: 'memo',
		label: '备注',
		type: 'basic'
	}],
	details: [{
		id: 'house.name',
		label: '仓库'
	}, {
		id: 'item.name',
		label: '品项'
	}, {
		id: 'composeBom.name',
		label: '产品BOM'
	}, {
		id: 'unit.name',
		label: '单位'
	}, {
		id: 'planTotal',
		label: '计划产量'
	}, {
		id: 'actualTotal',
		label: '实际产量'
	}, {
		id: 'planMakeCharge',
		label: '计划制造费用'
	}, {
		id: 'makeCharge',
		label: '实际制造费用'
	}, {
		id: 'manualCharge',
		label: '人工费用'
	}, {
		id: 'otherChargeTypeListNameList',
		label: '其他费用类型'
	}, {
		id: 'otherCharge',
		label: '其他费用'
	}, {
		id: 'productionCostPrice',
		label: '生产成本单价'
	}, {
		id: 'productionCost',
		label: '生产成本'
	}, {
		id: 'taxRate',
		label: '税率'
	}, {
		id: 'memo',
		label: '明细备注'
	}],
	subDetails: [{
		id: 'house.name',
		label: '仓库'
	}, {
		id: 'item.name',
		label: '配料'
	}, {
		id: 'unit.name',
		label: '单位'
	}, {
		id: 'planTotal',
		label: '计划用量'
	}, {
		id: 'actualTotal',
		label: '实际用量'
	}, {
		id: 'memo',
		label: '明细备注'
	}]
}
