export default {
	main: [{
		id: 'sysBillCode',
		label: '系统单号',
		type: 'basic'
	}, {
		id: 'userBillCode',
		label: '手工单号',
		type: 'basic'
	}, {
		id: 'billType',
		label: '单据类型',
		type: 'basic'
	}, {
		id: 'businessDate',
		label: '业务时间',
		type: 'basic'
	}, {
		id: 'organ.name',
		label: '付款机构',
		type: 'basic'
	}, {
		id: 'otherOrgan.name',
		label: '收款机构',
		type: 'basic'
	}, {
		id: 'department.name',
		label: '核算部门',
		type: 'basic'
	}, {
		id: 'operateMan.name',
		label: '经办人',
		type: 'basic'
	}, {
		id: 'memo',
		label: '备注',
		type: 'basic'
	}, {
		id: 'otherOrganName',
		label: '收款方名称',
		type: 'basic'
	}, {
		id: 'otherOrganBank',
		label: '收款方开户银行',
		type: 'basic'
	}, {
		id: 'otherOrganAccount',
		label: '收款银行账户名称',
		type: 'basic'
	}, {
		id: 'otherOrganBankNum',
		label: '收款银行账号',
		type: 'basic'
	}],
	details: [{
		id: 'settleWay',
		label: '结算方式'
	}, {
		id: 'accountName',
		label: '账户名称'
	}, {
		id: 'bankAccount',
		label: '银行账号'
	}, {
		id: 'bankName',
		label: '开户银行'
	}, {
		id: 'payMoney',
		label: '付款金额'
	}, {
		id: 'memo',
		label: '备注'
	}]
}
