//	const createFileMessage = function (file) {
//		return file.appendixUrl
//	}
export default {
	main: [{
		id: 'userBillCode',
		label: '手工单号',
		type: 'basic'
	}, {
		id: 'sysBillCode',
		label: '系统单号',
		type: 'basic'
	}, {
		id: 'billTypeName',
		label: '单据类型：',
		type: 'basic'
	}, {
		id: 'billBizTypeName',
		label: '业务类型',
		type: 'basic'
	}, {
		id: 'businessDate',
		label: '生产计划日期',
		type: 'basic'
	}, {
		id: 'organ.name',
		label: '加工机构',
		type: 'basic'
	}, {
		id: 'house.name',
		label: '仓库',
		type: 'basic'
	}, {
		id: 'operateMan.name',
		label: '经办人',
		type: 'basic'
	}, {
		id: 'memo',
		label: '备注',
		type: 'basic'
	}],
	details: [{
		id: 'workShop.name',
		label: '车间名称'
	}, {
		id: 'item.name',
		label: '品项'
	}, {
		id: 'item.spec',
		label: '规格'
	}, {
		id: 'itemUnit.name',
		label: '单位'
	}, {
		id: 'composeBom.name',
		label: '产品Bom'
	}, {
		id: 'resTechnologyLineDTO.name',
		label: '工艺路线'
	}, {
		id: 'planTotal',
		label: '计划产量'
	}, {
		id: 'memo',
		label: '明细备注'
	}, {
		id: 'planStartDate',
		label: '计划开工时间'
	}, {
		id: 'planEndDate',
		label: '计划完成时间'
	}]
}
